feat(OSPO): synchronise OSPO workflows

diff --git a/.github/workflows/oss-checker.yml b/.github/workflows/oss-checker.yml
--- a/.github/workflows/oss-checker.yml
+++ b/.github/workflows/oss-checker.yml
@@ -87,14 +87,14 @@ jobs:
             echo "OSS required file check failed."
             exit 1
           else
-            echo "All OSS files are present and customised."
+            echo "All OSS files are present and have been updated from their original templated content."
           fi
 
-      - name: Check for pull request and issue template files
+      - name: Check GitHub template files are present
         run: |
           echo "Checking for pull request and issue template files"
 
-          missing_recommended=()
+          missing_templates=()
 
           files_to_check=(
             ".github/PULL_REQUEST_TEMPLATE.md"
@@ -104,17 +104,21 @@ jobs:
 
           for file in "${files_to_check[@]}"; do
             if [ ! -f "$file" ]; then
-              missing_recommended+=("$file")
+              missing_templates+=("$file")
             fi
           done
 
-          if [ ${#missing_recommended[@]} -ne 0 ]; then
+          if [ ${#missing_templates[@]} -ne 0 ]; then
             echo ""
-            echo "Recommended template files not found:"
-            printf '  - %s\n' "${missing_recommended[@]}"
+            echo "Required GitHub template files not found:"
+            printf '  - %s\n' "${missing_templates[@]}"
             echo ""
             echo "These files help improve project collaboration and are considered best practice."
-            echo "Consider adding them to improve the developer experience."
+            echo "These need to be included in repository contents to improve the developer and repository consumer experience."
+
+            # Fail the job
+            echo "Missing required GitHub template files."
+            exit 1
           else
-            echo "All pull request and issue template files are present."
+            echo "Required pull request and issue template files present."
           fi
